/**
 * `tmuxd init` — write a `.env` for one of the three deployment shapes
 * (server, relay, client). The CLI is the canonical way to bootstrap
 * a tmuxd box; the .env templates in the repo are reference docs for
 * humans, but `tmuxd init` is what scripts should call.
 *
 * The output mirrors `.env.example` and `.env.client.example` exactly,
 * but with the operator's chosen values pre-filled and the unrelated
 * mode-comments stripped (only the chosen mode's values are present).
 *
 * Three modes share one writer:
 *
 *   server  → Mode A (HOST=127.0.0.1) or Mode B (HOST=0.0.0.0). The
 *             `--public` flag toggles to Mode B. TMUXD_RELAY is unset.
 *   relay   → Mode C. TMUXD_RELAY=1, HOST=0.0.0.0.
 *   client  → outbound .env (TMUXD_URL + tokens + host id/name). No
 *             HOST/PORT/JWT_SECRET, etc.
 *
 * Refuses to overwrite an existing .env unless --force; never writes
 * outside the CWD; never reads or modifies anything else.
 */
import { stat, writeFile } from 'node:fs/promises'
import { randomBytes } from 'node:crypto'
import { resolve } from 'node:path'

export type InitMode = 'server' | 'relay' | 'client'

export interface InitOptions {
    /** Working directory the .env file goes into. Defaults to process.cwd(). */
    cwd?: string
    /** Overwrite an existing .env. Default: refuse. */
    force?: boolean
    /** Output filename. Defaults to `.env`. */
    filename?: string

    // server / relay
    /** Pre-existing server token, or generate a fresh one if undefined. */
    serverToken?: string
    /** Mode B (`HOST=0.0.0.0`) instead of Mode A loopback for `init server`. */
    publicBind?: boolean
    /** TCP port. Default: 7681. */
    port?: number

    // client
    tmuxdUrl?: string
    userToken?: string
    hostId?: string
    hostName?: string
}

export interface InitResult {
    /** Absolute path to the file we wrote. */
    path: string
    /** Auto-generated server token (server / relay only); echo to user once. */
    generatedServerToken: string | null
}

const DEFAULT_PORT = 7681

/** 64 hex chars = 32 random bytes. Mirrors `openssl rand -hex 32`. */
function generateServerToken(): string {
    return randomBytes(32).toString('hex')
}

/**
 * Validate a candidate value before we paste it into a `.env` line. The
 * only structural risk is a literal newline (would break the dotenv
 * parser); we also forbid leading/trailing whitespace because dotenv
 * tools read those inconsistently across runtimes.
 */
function validateEnvValue(name: string, value: string): void {
    if (!value) throw new Error(`${name} must not be empty`)
    if (/[\r\n]/.test(value)) throw new Error(`${name} must not contain newlines`)
    if (value !== value.trim()) {
        throw new Error(`${name} must not have leading/trailing whitespace`)
    }
}

function renderServerEnv(opts: {
    serverToken: string
    relay: boolean
    host: string
    port: number
}): string {
    const lines: string[] = []
    lines.push('# tmuxd SERVER configuration')
    lines.push(`# Mode: ${opts.relay ? 'C — relay multi-user' : opts.host === '127.0.0.1' ? 'A — single-user local' : 'B — server + remote clients'}`)
    lines.push('# Generated by `tmuxd init`. See docs/deployment-modes.md.')
    lines.push('')
    lines.push('# Shared trust-circle token. Anyone with this can use this server.')
    lines.push('# Treat like a team password.')
    lines.push(`TMUXD_SERVER_TOKEN=${opts.serverToken}`)
    lines.push('')
    if (opts.relay) {
        lines.push('# Relay mode: refuse to host tmux sessions on this box.')
        lines.push('# The local host is hidden from every namespace; clients on')
        lines.push('# other machines provide all the sessions.')
        lines.push('TMUXD_RELAY=1')
        lines.push('')
    }
    lines.push('# Bind address.')
    lines.push(`HOST=${opts.host}`)
    lines.push('')
    lines.push('# HTTP port.')
    lines.push(`PORT=${opts.port}`)
    lines.push('')
    return lines.join('\n')
}

function renderClientEnv(opts: {
    tmuxdUrl: string
    serverToken: string
    userToken: string
    hostId?: string
    hostName?: string
}): string {
    const lines: string[] = []
    lines.push('# tmuxd CLIENT configuration')
    lines.push('# Generated by `tmuxd init client`. See .env.client.example for full reference.')
    lines.push('')
    lines.push('# The tmuxd server (or relay) URL. Use https:// in production.')
    lines.push(`TMUXD_URL=${opts.tmuxdUrl}`)
    lines.push('')
    lines.push('# Trust-circle token from the server admin (= server\'s TMUXD_SERVER_TOKEN).')
    lines.push(`TMUXD_SERVER_TOKEN=${opts.serverToken}`)
    lines.push('')
    lines.push('# Your personal token. Reuse the same value across all your devices')
    lines.push('# so they share a namespace. The server hashes it into your namespace.')
    lines.push(`TMUXD_USER_TOKEN=${opts.userToken}`)
    lines.push('')
    if (opts.hostId) {
        lines.push('# Stable host identifier. Letters/digits/dot/underscore/dash, ≤ 64 chars.')
        lines.push(`TMUXD_HOST_ID=${opts.hostId}`)
        lines.push('')
    }
    if (opts.hostName) {
        lines.push('# Display name shown in the web UI host list.')
        lines.push(`TMUXD_HOST_NAME=${opts.hostName}`)
        lines.push('')
    }
    return lines.join('\n')
}

/**
 * Write a `.env` file for the chosen mode. The caller is responsible
 * for echoing whatever stderr instructions are appropriate (e.g.
 * "save this generated server token"); this function is pure I/O.
 */
export async function writeEnvFile(mode: InitMode, opts: InitOptions = {}): Promise<InitResult> {
    // INIT_CWD is set by npm to the directory the user invoked `npm` in,
    // before npm chdir'd into the workspace. When `tmuxd init` is run via
    // `npm run tmuxd -- init server`, process.cwd() points at server/,
    // not where the user actually wants the .env to land. Honor INIT_CWD
    // when present and the explicit cwd opt is absent.
    const cwd = opts.cwd ?? process.env.INIT_CWD ?? process.cwd()
    const filename = opts.filename ?? '.env'
    const path = resolve(cwd, filename)

    if (!opts.force) {
        try {
            await stat(path)
            throw new Error(
                `${path} already exists. Pass --force to overwrite, or remove it first.`
            )
        } catch (err) {
            if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
        }
    }

    let body: string
    let generatedServerToken: string | null = null

    if (mode === 'server' || mode === 'relay') {
        let serverToken = opts.serverToken
        if (!serverToken) {
            serverToken = generateServerToken()
            generatedServerToken = serverToken
        }
        validateEnvValue('serverToken', serverToken)
        const port = opts.port ?? DEFAULT_PORT
        if (!Number.isInteger(port) || port < 1 || port > 65535) {
            throw new Error(`port must be an integer 1..65535, got ${port}`)
        }
        const isRelay = mode === 'relay'
        // Mode A vs Mode B selection for `init server`. `init relay`
        // implies public bind because a loopback-only relay is useless.
        const host = isRelay ? '0.0.0.0' : opts.publicBind ? '0.0.0.0' : '127.0.0.1'
        body = renderServerEnv({ serverToken, relay: isRelay, host, port })
    } else if (mode === 'client') {
        if (!opts.tmuxdUrl) throw new Error('init client requires --url <server-url>')
        if (!opts.serverToken) throw new Error('init client requires --server-token <secret>')
        if (!opts.userToken) throw new Error('init client requires --user-token <secret>')
        validateEnvValue('tmuxdUrl', opts.tmuxdUrl)
        validateEnvValue('serverToken', opts.serverToken)
        validateEnvValue('userToken', opts.userToken)
        if (opts.hostId) validateEnvValue('hostId', opts.hostId)
        if (opts.hostName) validateEnvValue('hostName', opts.hostName)
        body = renderClientEnv({
            tmuxdUrl: opts.tmuxdUrl,
            serverToken: opts.serverToken,
            userToken: opts.userToken,
            hostId: opts.hostId,
            hostName: opts.hostName
        })
    } else {
        throw new Error(`unknown init mode: ${mode as string}`)
    }

    await writeFile(path, body, { mode: 0o600 })

    return { path, generatedServerToken }
}
